CREATE TABLE "sales_order"(
	"SALESORDERID" VARCHAR(10) NOT NULL,
	"HISTORY.CREATEDBY.EMPLOYEEID" VARCHAR(10),
	"HISTORY.CREATEDAT" DATE,
	"HISTORY.CHANGEDBY.EMPLOYEEID" VARCHAR(10),
	"HISTORY.CHANGEDAT" DATE,
	"NOTEID" VARCHAR(10),
	"PARTNER.PARTNERID" VARCHAR(10),
	"CURRENCY" VARCHAR(5),
	"GROSSAMOUNT" DECIMAL(15, 2),
	"NETAMOUNT" DECIMAL(15, 2),
	"TAXAMOUNT" DECIMAL(15, 2),
	"LIFECYCLESTATUS" VARCHAR(1),
	"BILLINGSTATUS" VARCHAR(1),
	"DELIVERYSTATUS" VARCHAR(1),
	PRIMARY KEY (
		"SALESORDERID"
	)
);
